// Command dashboards writes, lints and checks gravel's Grafana dashboards (ADR-0009).
//
//	go run ./internal/tools/dashboards gen   [--out deploy/observability/grafana/dashboards]
//	go run ./internal/tools/dashboards rules [--dir …]   a Prometheus rules file, one rule per panel query, for promtool
//	go run ./internal/tools/dashboards check --grafana http://127.0.0.1:3000 --password-file F [--dir …] [--skip gravel-bot]
//
// gen renders the definitions in defs.go; make generate runs it and CI fails on a stale file.
// rules turns every panel's query, variables and macros filled in, into a recording rule, so
// `promtool check rules` parses every expression. check asks a running Grafana, through its
// own datasource, for every panel's data: a panel with no data fails unless it is marked
// optional, which is reported with the reason. An operator can run check against their own
// deployment.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

const defaultDir = "deploy/observability/grafana/dashboards"

func main() {
	os.Exit(run(context.Background(), os.Args[1:], os.Stdout, os.Stderr))
}

func run(ctx context.Context, args []string, stdout, stderr io.Writer) int {
	if len(args) == 0 {
		fmt.Fprintln(stderr, "usage: dashboards gen|rules|check [flags]")
		return 2
	}
	fs := flag.NewFlagSet("dashboards "+args[0], flag.ContinueOnError)
	fs.SetOutput(stderr)
	dir := fs.String("dir", defaultDir, "the dashboards directory")
	out := fs.String("out", defaultDir, "gen: where to write the dashboards")
	grafana := fs.String("grafana", "http://127.0.0.1:3000", "check: Grafana's address")
	user := fs.String("user", "admin", "check: Grafana user")
	passwordFile := fs.String("password-file", "", "check: a file holding the user's password")
	skip := fs.String("skip", "", "check: comma-separated dashboard uids to leave out (e.g. gravel-bot where no bot runs)")
	if err := fs.Parse(args[1:]); err != nil {
		return 2
	}
	var err error
	switch args[0] {
	case "gen":
		err = gen(*out)
	case "rules":
		err = rules(*dir, stdout)
	case "check":
		var pw []byte
		if *passwordFile == "" {
			err = errors.New("check needs --password-file")
			break
		}
		if pw, err = os.ReadFile(*passwordFile); err != nil {
			break
		}
		c := checker{base: strings.TrimRight(*grafana, "/"), user: *user, password: strings.TrimSpace(string(pw)), http: &http.Client{Timeout: 15 * time.Second}, out: stdout}
		err = c.check(ctx, *dir, splitList(*skip))
	default:
		fmt.Fprintf(stderr, "dashboards: unknown command %q\n", args[0])
		return 2
	}
	if err != nil {
		fmt.Fprintln(stderr, "dashboards:", err)
		return 1
	}
	return 0
}

func splitList(s string) map[string]bool {
	out := map[string]bool{}
	for _, v := range strings.Split(s, ",") {
		if v = strings.TrimSpace(v); v != "" {
			out[v] = true
		}
	}
	return out
}

func gen(out string) error {
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	for _, d := range dashboards() {
		b, err := json.MarshalIndent(d.render(), "", "  ")
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(out, d.UID+".json"), append(b, '\n'), 0o644); err != nil {
			return err
		}
	}
	return nil
}

var ruleName = regexp.MustCompile(`[^a-z0-9_]`)

func rules(dir string, w io.Writer) error {
	ds, err := readDashboards(dir)
	if err != nil {
		return err
	}
	vars := map[string]string{"job": "job", "instance": ".+"}
	fmt.Fprintln(w, "# Generated by internal/tools/dashboards rules: every panel query as a rule, for promtool.")
	fmt.Fprintln(w, "groups:")
	for _, d := range ds {
		fmt.Fprintf(w, "  - name: %s\n    rules:\n", d.UID)
		for _, p := range d.Panels {
			for _, t := range p.Targets {
				name := ruleName.ReplaceAllString(strings.ToLower(fmt.Sprintf("dashboard_%s_%d_%s", d.UID, p.ID, t.RefID)), "_")
				expr, _ := json.Marshal(expand(t.Expr, vars)) // a JSON string is a valid YAML scalar
				fmt.Fprintf(w, "      - record: %s\n        expr: %s\n", name, expr)
			}
		}
	}
	return nil
}

type checker struct {
	base, user, password string
	http                 *http.Client
	out                  io.Writer
}

func (c checker) do(ctx context.Context, method, path string, body any, v any) error {
	var r io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return err
		}
		r = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.base+path, r)
	if err != nil {
		return err
	}
	req.SetBasicAuth(c.user, c.password)
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.http.Do(req)
	if err != nil {
		return err
	}
	defer func() { _ = resp.Body.Close() }()
	b, _ := io.ReadAll(io.LimitReader(resp.Body, 8<<20))
	if resp.StatusCode/100 != 2 {
		return fmt.Errorf("%s %s: %s: %s", method, path, resp.Status, strings.TrimSpace(string(b)))
	}
	if v == nil {
		return nil
	}
	return json.Unmarshal(b, v)
}

func (c checker) check(ctx context.Context, dir string, skip map[string]bool) error {
	ds, err := readDashboards(dir)
	if err != nil {
		return err
	}
	var sources []struct{ UID, Type string }
	if err := c.do(ctx, http.MethodGet, "/api/datasources", nil, &sources); err != nil {
		return err
	}
	dsUID := ""
	for _, s := range sources {
		if s.Type == "prometheus" {
			dsUID = s.UID
			break
		}
	}
	if dsUID == "" {
		return errors.New("grafana has no prometheus datasource")
	}
	failed := 0
	for _, d := range ds {
		if skip[d.UID] {
			fmt.Fprintf(c.out, "%s: skipped\n", d.UID)
			continue
		}
		// Provisioned: Grafana serves it under its uid.
		if err := c.do(ctx, http.MethodGet, "/api/dashboards/uid/"+url.PathEscape(d.UID), nil, nil); err != nil {
			fmt.Fprintf(c.out, "FAIL %s: not provisioned: %v\n", d.UID, err)
			failed++
			continue
		}
		job, err := c.job(ctx, dsUID, d)
		if err != nil {
			fmt.Fprintf(c.out, "FAIL %s: %v\n", d.UID, err)
			failed++
			continue
		}
		vars := map[string]string{"job": job, "instance": ".+"}
		for _, p := range d.Panels {
			if p.Type == "row" {
				continue
			}
			has, err := c.panelHasData(ctx, dsUID, p, vars)
			switch {
			case err != nil:
				fmt.Fprintf(c.out, "FAIL %s / %s: %v\n", d.UID, p.Title, err)
				failed++
			case has:
				fmt.Fprintf(c.out, "ok   %s / %s\n", d.UID, p.Title)
			case p.Optional != "":
				fmt.Fprintf(c.out, "--   %s / %s: no data (expected when %s)\n", d.UID, p.Title, p.Optional)
			default:
				fmt.Fprintf(c.out, "FAIL %s / %s: no data\n", d.UID, p.Title)
				failed++
			}
		}
	}
	if failed > 0 {
		return fmt.Errorf("%d panel(s) failed", failed)
	}
	return nil
}

var labelValues = regexp.MustCompile(`^label_values\(([a-z_:][a-z0-9_:]*), job\)$`)

// job resolves the dashboard's job variable as Grafana would: the first job its build-info
// metric carries.
func (c checker) job(ctx context.Context, dsUID string, d fileDashboard) (string, error) {
	var buildInfo string
	for _, v := range d.Templating.List {
		if v.Name == "job" {
			if m := labelValues.FindStringSubmatch(v.Definition); m != nil {
				buildInfo = m[1]
			}
		}
	}
	if buildInfo == "" {
		return "", errors.New("no job variable of the form label_values(<metric>, job)")
	}
	var resp struct {
		Data []string `json:"data"`
	}
	path := "/api/datasources/proxy/uid/" + url.PathEscape(dsUID) + "/api/v1/label/job/values?match[]=" + url.QueryEscape(buildInfo)
	if err := c.do(ctx, http.MethodGet, path, nil, &resp); err != nil {
		return "", err
	}
	if len(resp.Data) == 0 {
		return "", fmt.Errorf("no job has %s: is it scraped?", buildInfo)
	}
	sort.Strings(resp.Data)
	return resp.Data[0], nil
}

// panelHasData runs each of the panel's queries, instant, through Grafana; any series with a
// sample counts. A query Grafana or Prometheus refuses is an error, optional or not.
func (c checker) panelHasData(ctx context.Context, dsUID string, p filePanel, vars map[string]string) (bool, error) {
	has := false
	for _, t := range p.Targets {
		body := map[string]any{
			"from": "now-15m", "to": "now",
			"queries": []any{map[string]any{
				"refId": t.RefID, "datasource": map[string]any{"type": "prometheus", "uid": dsUID},
				"expr": expand(t.Expr, vars), "instant": true, "range": false,
			}},
		}
		var resp struct {
			Results map[string]struct {
				Error  string `json:"error"`
				Frames []struct {
					Data struct {
						Values [][]any `json:"values"`
					} `json:"data"`
				} `json:"frames"`
			} `json:"results"`
		}
		if err := c.do(ctx, http.MethodPost, "/api/ds/query", body, &resp); err != nil {
			return false, fmt.Errorf("%s: %w", t.RefID, err)
		}
		r := resp.Results[t.RefID]
		if r.Error != "" {
			return false, fmt.Errorf("%s: %s", t.RefID, r.Error)
		}
		for _, f := range r.Frames {
			for _, col := range f.Data.Values {
				if len(col) > 0 {
					has = true
				}
			}
		}
	}
	return has, nil
}
